[project]
name = "obsidian-watchdog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "duckdb>=1.2.2",
    "pydantic-ai>=0.1.11",
    "pyyaml>=6.0.2",
    "tinydb>=4.8.2",
    "watchdog>=6.0.0",
]
